# This rule is not used by the project eventbus-failover-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to failover.scheduler.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: eventbus-failover-controller
    app.kubernetes.io/managed-by: kustomize
  name: eventbusobservation-viewer-role
rules:
- apiGroups:
  - failover.scheduler.dev
  resources:
  - eventbusobservations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - failover.scheduler.dev
  resources:
  - eventbusobservations/status
  verbs:
  - get
