---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nats.failover.io
  resources:
  - natsprofiles
  - observations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nats.failover.io
  resources:
  - natsprofiles/finalizers
  - observations/finalizers
  verbs:
  - update
- apiGroups:
  - nats.failover.io
  resources:
  - natsprofiles/status
  - observations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy.karmada.io
  resources:
  - propagationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
