//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventBusCandidate) DeepCopyInto(out *EventBusCandidate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventBusCandidate.
func (in *EventBusCandidate) DeepCopy() *EventBusCandidate {
	if in == nil {
		return nil
	}
	out := new(EventBusCandidate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventBusObservation) DeepCopyInto(out *EventBusObservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventBusObservation.
func (in *EventBusObservation) DeepCopy() *EventBusObservation {
	if in == nil {
		return nil
	}
	out := new(EventBusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventBusObservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventBusObservationList) DeepCopyInto(out *EventBusObservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EventBusObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventBusObservationList.
func (in *EventBusObservationList) DeepCopy() *EventBusObservationList {
	if in == nil {
		return nil
	}
	out := new(EventBusObservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventBusObservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventBusObservationSpec) DeepCopyInto(out *EventBusObservationSpec) {
	*out = *in
	out.EventBusRef = in.EventBusRef
	out.Primary = in.Primary
	if in.Candidates != nil {
		in, out := &in.Candidates, &out.Candidates
		*out = make([]EventBusCandidate, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventBusObservationSpec.
func (in *EventBusObservationSpec) DeepCopy() *EventBusObservationSpec {
	if in == nil {
		return nil
	}
	out := new(EventBusObservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventBusObservationStatus) DeepCopyInto(out *EventBusObservationStatus) {
	*out = *in
	out.PrimaryStatus = in.PrimaryStatus
	if in.CandidateStatuses != nil {
		in, out := &in.CandidateStatuses, &out.CandidateStatuses
		*out = make([]EventBusObservedStatus, len(*in))
		copy(*out, *in)
	}
	if in.SelectedStandby != nil {
		in, out := &in.SelectedStandby, &out.SelectedStandby
		*out = new(SelectedStandby)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventBusObservationStatus.
func (in *EventBusObservationStatus) DeepCopy() *EventBusObservationStatus {
	if in == nil {
		return nil
	}
	out := new(EventBusObservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventBusObservedStatus) DeepCopyInto(out *EventBusObservedStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventBusObservedStatus.
func (in *EventBusObservedStatus) DeepCopy() *EventBusObservedStatus {
	if in == nil {
		return nil
	}
	out := new(EventBusObservedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventBusRef) DeepCopyInto(out *EventBusRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventBusRef.
func (in *EventBusRef) DeepCopy() *EventBusRef {
	if in == nil {
		return nil
	}
	out := new(EventBusRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectedStandby) DeepCopyInto(out *SelectedStandby) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectedStandby.
func (in *SelectedStandby) DeepCopy() *SelectedStandby {
	if in == nil {
		return nil
	}
	out := new(SelectedStandby)
	in.DeepCopyInto(out)
	return out
}
